// catch error
run().catch((err) => console.log(err));

// function to get data
async function run() {}
